### PR TITLE
Add some profane words in PT-BR

### PR DESCRIPTION
**Pull request by SteffanoP**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks @SteffanoP! The tests are failing because we display the count (currently `140` in several places). Could you find all occurrences of `140` relating to Portuguese in the project, and change them to 148?

**Comment by SteffanoP** [comment]
> Thanks @SteffanoP! The tests are failing because we display the count (currently `140` in several places). Could you find all occurrences of `140` relating to Portuguese in the project, and change them to 148?

Done!

**Comment by wooorm** [comment]
@SteffanoP Thanks, but I also meant the other places: https://github.com/words/cuss/search?q=140&unscoped_q=140. That test is just there to make sure to also update the other places ;)

**Comment by SteffanoP** [comment]
> @SteffanoP Thanks, but I also meant the other places: https://github.com/words/cuss/search?q=140&unscoped_q=140. That test is just there to make sure to also update the other places ;)

Sorry, i was just so automatic earlier today.

I just commited, should be fine now.

**Comment by wooorm** [comment]
Awesome!

**Comment by wooorm** [comment]
Release as 1.12.0!

**Pull request merged**
