### PR TITLE
en: add 'trap'

### PR DESCRIPTION
**Pull request by integralLeft**
Added 'trap' with profanity rating of '1'.

### CODE REVIEW

**Comment by wooorm** [comment]
Any reason for `1`? I personally haven’t ever trap used as a profanity, whereas I hear it in clean text more often, so I’d think `0`.

**Comment by integralLeft** [comment]
Maybe it's the circles I move in, but I tend to hear it more as a profanity, specifically regarding crossdressing men, whereas in a purely textual context I find that it's not too common itself. Let me know if you want me to change it, though.

**Comment by RichardLitt** [comment]
I'd put it at a maybe. It's rare as a profanity, and only online AFAIK.

**Comment by integralLeft** [comment]
Should this be merged, then, with the current rating of 1?

**Comment by RichardLitt** [comment]
Yes. 1 Seems fine to me. LGTM!

**Comment by wooorm** [comment]
Yes, 1 is fine, I’ll merge and release soon!

**Comment by wooorm** [comment]
Thanks, released!

**Comment by integralLeft** [comment]
Nice!

**Pull request merged**
