### PR TITLE
Add Portuguese(Portugal) bad words

### PR DESCRIPTION
**Pull request by namadnuno**
Added the most popular Portuguese bad words

### CODE REVIEW

**Comment by wooorm** [comment]
Nice! You should setup GitHub so that it knows who you are in Git, that way you’ll get credits for your work: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

Btw, are you interested in adding more words? If so, would looking at the Brazilian version be a source of inspiration?

**Comment by namadnuno** [comment]
> Nice! You should setup GitHub so that it knows who you are in Git, that way you’ll get credits for your work: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address
> 
> Btw, are you interested in adding more words? If so, would looking at the Brazilian version be a source of inspiration?

@wooorm Sorry, I forgot to setup that in this new machine, thank you for pointing it out. Yes, I would want to add more Portuguese words, just added the most common ones. I wanted to use this package in one of my project that's why I just added these (~35 words). If you want I can try to add more before you merge or if it's ok, merge it, and I will add more until the end of the week.

**Comment by wooorm** [comment]
Nice start! Do you want me to merge and release it now? Or do you want to continue working on it and we release everything when you’re done? Both are fine with me!

**Comment by namadnuno** [comment]
> Nice start! Do you want me to merge and release it now? Or do you want to continue working on it and we release everything when you’re done? Both are fine with me!

Thank you!! Please merge it, I will come back soon to add more words 👊

**Comment by wooorm** [comment]
Released in 1.19.0! https://github.com/words/cuss/releases/tag/1.19.0

**Pull request merged**
