### PR TITLE
removed "faire" that means "do"

### PR DESCRIPTION
**Pull request by AlthaelFR**
it's way too stupid to have this word

### CODE REVIEW

**Comment by AlthaelFR** [comment]
like the sentence : Je vais faire des pattes, with means I will cook pastas :')
It's stupid to block this word

**Comment by AlthaelFR** [comment]
please could you accept this request ??

**Comment by Murderlon** [comment]
@AlthaelFR thanks for the PR. Words in cuss rated `0` are very unlikely to be used as a profanity, but it's not an impossibility. Consider the following sentences from [insultes en français](https://fr.wiktionary.org/wiki/Cat%C3%A9gorie:Insultes_en_fran%C3%A7ais):

> - aller se faire enculer
> - aller se faire endauffer
> - aller se faire foutre
> - aller se faire mettre

Considering the word can be used to construct a profane sentence, I'd say we keep it for completeness sake. However, I do not speak french so I'm uncertain where we would draw the line with words like this. Do you have a reasoning on what that differentiation should be?

**Comment by wooorm** [comment]
@cynferdd I believe you authored this file. What’s your opinion?

**Comment by wooorm** [comment]
@cynferdd @AlthaelFR Ping!

**Comment by wooorm** [comment]
Closed due to no response.

**Pull request closed without merging**
