### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by AlthaelFR**
Removed the mandela words that are not supposed to be here and added some

### CODE REVIEW

**Comment by wooorm** [comment]
Could you expand on why you’re removing those? E.g., https://fr.wiktionary.org/wiki/libérer_Mandela

**Comment by AlthaelFR** [comment]
It only means rescue Mandela there is no racist word with it :')
And no one think that is a racist word

**Comment by wooorm** [comment]
@AlthaelFR Did you read the link I posted above? I don’t properly speak French but I get the gist of what’s referenced there.

**Comment by wooorm** [comment]
Closed due to no response.

**Pull request closed without merging**
